import fs from "node:fs";
import { Project, SyntaxKind } from "ts-morph";

/**
 * jsonld-website-fixer.ts와 완전히 동일한 스켈레톤(의도적 복제 — og-fixer.ts가 canonical-fixer.ts를
 * 복제한 것과 같은 이유, 이 저장소의 기존 관례). 차이는 삽입하는 JSON-LD 타입(WebSite→Organization)과
 * 마커 문자열뿐이다.
 *
 * - 대상은 루트 레이아웃 파일 1곳뿐(App Router 규칙상 위치가 결정론적).
 * - `<body>` 요소가 정확히 1개일 때만 진행(0개·2개 이상은 fail-closed).
 * - 삽입값은 `orgName` 하나뿐 — 호출부(`fix-orchestrator/plan.ts`)가 이미 렌더된 홈페이지 title을
 *   그대로 넘긴다(값 발명 없음). logo·sameAs(SNS 링크)·주소는 페이지에 원본이 없어 의도적으로
 *   넣지 않는다 — Organization의 name 수준까지만 자동수정 가능하다는 설계 결정 그대로.
 */
export const ORGANIZATION_MARKER = "Generated by SeoMedic — R-JSONLD-ORG-MISSING";

export interface OrganizationFixPlan {
  applicable: boolean;
  reason: string;
  originalText?: string;
  updatedText?: string;
}

/** jsonld-website-fixer.ts의 escapeForInlineScript와 동일 — M7(소스 주입 방지). */
function escapeForInlineScript(json: string): string {
  return json.replace(/</g, "\\u003c");
}

function buildScriptTag(orgName: string): string {
  const jsonLd = escapeForInlineScript(JSON.stringify({ "@context": "https://schema.org", "@type": "Organization", name: orgName }));
  return (
    `{/* ${ORGANIZATION_MARKER} — 재실행돼도 이 마커가 있으면 덮어쓰지 않습니다 */}\n` +
    `      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: ${JSON.stringify(jsonLd)} }} />`
  );
}

export function planOrganizationFix(filePath: string, orgName: string): OrganizationFixPlan {
  if (!fs.existsSync(filePath)) {
    return { applicable: false, reason: "루트 레이아웃 파일을 찾지 못했습니다" };
  }
  const originalText = fs.readFileSync(filePath, "utf-8");
  if (originalText.includes(ORGANIZATION_MARKER)) {
    return {
      applicable: false,
      reason: "이미 SeoMedic이 생성한 Organization JSON-LD가 존재합니다(멱등)",
      originalText,
      updatedText: originalText,
    };
  }

  const project = new Project({ useInMemoryFileSystem: true, compilerOptions: { jsx: 4 } }); // 4 = react-jsx
  const sourceFile = project.createSourceFile(filePath, originalText);

  const bodyElements = sourceFile
    .getDescendantsOfKind(SyntaxKind.JsxElement)
    .filter((el) => el.getOpeningElement().getTagNameNode().getText() === "body");

  if (bodyElements.length !== 1) {
    return {
      applicable: false,
      reason: `<body> 요소를 정확히 1개 찾지 못해(${bodyElements.length}개 발견) 안전하게 판단할 수 없어 건너뜁니다`,
      originalText,
    };
  }

  const bodyEl = bodyElements[0];
  const openTag = bodyEl.getOpeningElement().getText();
  const closeTag = bodyEl.getClosingElement().getText();
  const innerText = bodyEl.getJsxChildren().map((c) => c.getText()).join("");

  bodyEl.replaceWithText(`${openTag}${innerText}\n      ${buildScriptTag(orgName)}\n    ${closeTag}`);
  sourceFile.formatText();

  return { applicable: true, reason: "루트 레이아웃에 Organization JSON-LD 추가를 제안합니다", originalText, updatedText: sourceFile.getFullText() };
}

/** plan에서 확정된 텍스트를 실제로 디스크에 쓴다(적용 전 재검증은 오케스트레이터의 책임). */
export function writeOrganizationFix(filePath: string, updatedText: string): void {
  fs.writeFileSync(filePath, updatedText, "utf-8");
}
